services:
   keycloak:
      image: quay.io/keycloak/keycloak:18.0.2
      environment:
         - KEYCLOAK_ADMIN=admin
         - KEYCLOAK_ADMIN_PASSWORD=admin
      ports:
         - "8181:8080"
      networks:
         - backend
      command:
         - start-dev
      volumes:
         - ./keycloak-custom-theme:/opt/keycloak/themes/my-custom-theme

networks:
   backend:
      driver: bridge
